// ===== 中1 えいごドリル：問題データ =====
// 光村「Here We Go!」の単元構成に寄せた中1標準のオリジナル問題。
// 教科書と完全一致ではありません。あとから自由に追加・差し替えできます。
//
// words: { en:英単語, ja:日本語 }
// sentences: { ja:日本語文, tokens:[正しい語順の英単語] }
//   ※ ピリオドや「？」は自動表示。tokens には単語だけを入れる。先頭は大文字で。

const UNITS = [
  // ============================================================
  {
    id: "u1",
    title: "Unit 1　自己紹介（be動詞 am / are）",
    words: [
      { en: "I",       ja: "私は" },
      { en: "you",     ja: "あなたは" },
      { en: "am",      ja: "〜です（I のとき）" },
      { en: "are",     ja: "〜です（you のとき）" },
      { en: "name",    ja: "名前" },
      { en: "friend",  ja: "友達" },
      { en: "student", ja: "生徒・学生" },
      { en: "happy",   ja: "うれしい" },
      { en: "from",    ja: "〜出身で" },
      { en: "nice",    ja: "素敵な・良い" },
      { en: "this",    ja: "これは" },
      { en: "is",      ja: "〜です（he / it のとき）" },
      { en: "hungry",  ja: "おなかがすいた" },
      { en: "fine",    ja: "元気な" },
      { en: "great",   ja: "すばらしい" },
    ],
    sentences: [
      { ja: "私は学生です。",         tokens: ["I", "am", "a", "student"] },
      { ja: "あなたは私の友達です。",   tokens: ["You", "are", "my", "friend"] },
      { ja: "私はうれしいです。",       tokens: ["I", "am", "happy"] },
      { ja: "私はケンです。",          tokens: ["I", "am", "Ken"] },
      { ja: "あなたは素敵です。",       tokens: ["You", "are", "nice"] },
      { ja: "私は大阪出身です。",       tokens: ["I", "am", "from", "Osaka"] },
      { ja: "これはペンです。",         tokens: ["This", "is", "a", "pen"] },
      { ja: "私は元気です。",          tokens: ["I", "am", "fine"] },
      { ja: "私はおなかがすいています。", tokens: ["I", "am", "hungry"] },
      { ja: "あなたはすばらしいです。",  tokens: ["You", "are", "great"] },
    ],
  },

  // ============================================================
  {
    id: "u2",
    title: "Unit 2　一般動詞（like / play / have）",
    words: [
      { en: "like",   ja: "好きだ" },
      { en: "play",   ja: "（スポーツ・楽器を）する" },
      { en: "have",   ja: "持っている・飼っている" },
      { en: "want",   ja: "ほしい" },
      { en: "eat",    ja: "食べる" },
      { en: "study",  ja: "勉強する" },
      { en: "know",   ja: "知っている" },
      { en: "go",     ja: "行く" },
      { en: "speak",  ja: "話す" },
      { en: "music",  ja: "音楽" },
      { en: "drink",  ja: "飲む" },
      { en: "use",    ja: "使う" },
      { en: "help",   ja: "助ける" },
      { en: "make",   ja: "作る" },
      { en: "tennis", ja: "テニス" },
    ],
    sentences: [
      { ja: "私はサッカーが好きです。",       tokens: ["I", "like", "soccer"] },
      { ja: "私は毎日英語を勉強します。",     tokens: ["I", "study", "English", "every", "day"] },
      { ja: "私はギターを弾きます。",         tokens: ["I", "play", "the", "guitar"] },
      { ja: "私は犬を飼っています。",         tokens: ["I", "have", "a", "dog"] },
      { ja: "私は音楽が好きです。",           tokens: ["I", "like", "music"] },
      { ja: "私は朝ごはんを食べます。",       tokens: ["I", "eat", "breakfast"] },
      { ja: "私は水を飲みます。",             tokens: ["I", "drink", "water"] },
      { ja: "私はテニスをします。",           tokens: ["I", "play", "tennis"] },
      { ja: "私は数学が好きです。",           tokens: ["I", "like", "math"] },
      { ja: "私は新しいかばんがほしいです。", tokens: ["I", "want", "a", "new", "bag"] },
    ],
  },

  // ============================================================
  {
    id: "u3",
    title: "Unit 3　名詞の複数形と数",
    words: [
      { en: "many",   ja: "たくさんの" },
      { en: "some",   ja: "いくつかの" },
      { en: "book",   ja: "本" },
      { en: "apple",  ja: "りんご" },
      { en: "pen",    ja: "ペン" },
      { en: "two",    ja: "2つの" },
      { en: "three",  ja: "3つの" },
      { en: "cat",    ja: "ねこ" },
      { en: "box",    ja: "箱" },
      { en: "dog",    ja: "犬" },
      { en: "four",   ja: "4つの" },
      { en: "five",   ja: "5つの" },
      { en: "orange", ja: "オレンジ" },
      { en: "bird",   ja: "鳥" },
      { en: "ball",   ja: "ボール" },
    ],
    sentences: [
      { ja: "私は2匹の犬を飼っています。",   tokens: ["I", "have", "two", "dogs"] },
      { ja: "私はりんごが好きです。",         tokens: ["I", "like", "apples"] },
      { ja: "私はたくさんの本を持っています。", tokens: ["I", "have", "many", "books"] },
      { ja: "私は3冊のノートを持っています。", tokens: ["I", "have", "three", "notebooks"] },
      { ja: "私はねこが好きです。",           tokens: ["I", "like", "cats"] },
      { ja: "私はペンを2本持っています。",     tokens: ["I", "have", "two", "pens"] },
      { ja: "私は4個のりんごを持っています。", tokens: ["I", "have", "four", "apples"] },
      { ja: "私は鳥が好きです。",             tokens: ["I", "like", "birds"] },
      { ja: "私は5冊の本を読みます。",         tokens: ["I", "read", "five", "books"] },
      { ja: "私はボールを3個持っています。",   tokens: ["I", "have", "three", "balls"] },
    ],
  },

  // ============================================================
  {
    id: "u4",
    title: "Unit 4　疑問詞（What / Who / Where）",
    words: [
      { en: "what",     ja: "何" },
      { en: "who",      ja: "だれ" },
      { en: "where",    ja: "どこ" },
      { en: "when",     ja: "いつ" },
      { en: "how",      ja: "どうやって・どのくらい" },
      { en: "why",      ja: "なぜ" },
      { en: "which",    ja: "どちら" },
      { en: "whose",    ja: "だれの" },
      { en: "time",     ja: "時間" },
      { en: "color",    ja: "色" },
      { en: "today",    ja: "今日" },
      { en: "favorite", ja: "お気に入りの" },
      { en: "subject",  ja: "教科" },
      { en: "sport",    ja: "スポーツ" },
      { en: "animal",   ja: "動物" },
    ],
    sentences: [
      { ja: "あなたは何が好きですか。",             tokens: ["What", "do", "you", "like"] },
      { ja: "これは何ですか。",                     tokens: ["What", "is", "this"] },
      { ja: "あなたはどこの出身ですか。",           tokens: ["Where", "are", "you", "from"] },
      { ja: "あなたはだれですか。",                 tokens: ["Who", "are", "you"] },
      { ja: "今何時ですか。",                       tokens: ["What", "time", "is", "it"] },
      { ja: "あなたはサッカーが好きですか。",       tokens: ["Do", "you", "like", "soccer"] },
      { ja: "あなたのお気に入りの教科は何ですか。", tokens: ["What", "is", "your", "favorite", "subject"] },
      { ja: "あなたはいつ勉強しますか。",           tokens: ["When", "do", "you", "study"] },
      { ja: "あなたはどんなスポーツが好きですか。", tokens: ["What", "sport", "do", "you", "like"] },
      { ja: "これは何色ですか。",                   tokens: ["What", "color", "is", "this"] },
    ],
  },

  // ============================================================
  {
    id: "u5",
    title: "Unit 5　助動詞 can（〜できる）",
    words: [
      { en: "can",   ja: "〜できる" },
      { en: "swim",  ja: "泳ぐ" },
      { en: "run",   ja: "走る" },
      { en: "sing",  ja: "歌う" },
      { en: "cook",  ja: "料理する" },
      { en: "dance", ja: "踊る" },
      { en: "read",  ja: "読む" },
      { en: "write", ja: "書く" },
      { en: "jump",  ja: "跳ぶ" },
      { en: "fast",  ja: "速く" },
      { en: "well",  ja: "上手に" },
      { en: "ski",   ja: "スキーをする" },
      { en: "draw",  ja: "（絵を）描く" },
      { en: "climb", ja: "登る" },
      { en: "high",  ja: "高く" },
    ],
    sentences: [
      { ja: "私は泳ぐことができます。",       tokens: ["I", "can", "swim"] },
      { ja: "私は速く走ることができます。",   tokens: ["I", "can", "run", "fast"] },
      { ja: "あなたは上手に歌えます。",       tokens: ["You", "can", "sing", "well"] },
      { ja: "私はギターを弾けます。",         tokens: ["I", "can", "play", "the", "guitar"] },
      { ja: "あなたは英語を話せますか。",     tokens: ["Can", "you", "speak", "English"] },
      { ja: "私はピアノを弾けます。",         tokens: ["I", "can", "play", "the", "piano"] },
      { ja: "私はスキーができます。",         tokens: ["I", "can", "ski"] },
      { ja: "私は絵を上手に描けます。",       tokens: ["I", "can", "draw", "well"] },
      { ja: "彼は高く跳べます。",             tokens: ["He", "can", "jump", "high"] },
      { ja: "あなたは速く泳げますか。",       tokens: ["Can", "you", "swim", "fast"] },
    ],
  },

  // ============================================================
  {
    id: "u6",
    title: "Unit 6　三人称単数（he / she + s）",
    words: [
      { en: "he",      ja: "彼は" },
      { en: "she",     ja: "彼女は" },
      { en: "likes",   ja: "好む（三単現）" },
      { en: "plays",   ja: "する（三単現）" },
      { en: "has",     ja: "持っている（三単現）" },
      { en: "watch",   ja: "見る" },
      { en: "live",    ja: "住む" },
      { en: "teacher", ja: "先生" },
      { en: "mother",  ja: "母" },
      { en: "father",  ja: "父" },
      { en: "studies", ja: "勉強する（三単現）" },
      { en: "goes",    ja: "行く（三単現）" },
      { en: "sister",  ja: "姉・妹" },
      { en: "brother", ja: "兄・弟" },
      { en: "speaks",  ja: "話す（三単現）" },
    ],
    sentences: [
      { ja: "彼はサッカーが好きです。",       tokens: ["He", "likes", "soccer"] },
      { ja: "彼女はピアノを弾きます。",       tokens: ["She", "plays", "the", "piano"] },
      { ja: "彼は犬を飼っています。",         tokens: ["He", "has", "a", "dog"] },
      { ja: "私の母は英語を教えます。",       tokens: ["My", "mother", "teaches", "English"] },
      { ja: "彼女は東京に住んでいます。",     tokens: ["She", "lives", "in", "Tokyo"] },
      { ja: "私の父はテレビを見ます。",       tokens: ["My", "father", "watches", "TV"] },
      { ja: "彼は毎日英語を勉強します。",     tokens: ["He", "studies", "English", "every", "day"] },
      { ja: "彼女は学校に行きます。",         tokens: ["She", "goes", "to", "school"] },
      { ja: "私の姉は音楽が好きです。",       tokens: ["My", "sister", "likes", "music"] },
      { ja: "彼は英語を話します。",           tokens: ["He", "speaks", "English"] },
    ],
  },

  // ============================================================
  {
    id: "u7",
    title: "Unit 7　現在進行形（be + ~ing）",
    words: [
      { en: "now",      ja: "今" },
      { en: "running",  ja: "走っている" },
      { en: "playing",  ja: "している" },
      { en: "eating",   ja: "食べている" },
      { en: "studying", ja: "勉強している" },
      { en: "reading",  ja: "読んでいる" },
      { en: "watching", ja: "見ている" },
      { en: "singing",  ja: "歌っている" },
      { en: "sleeping", ja: "眠っている" },
      { en: "cooking",  ja: "料理している" },
      { en: "writing",  ja: "書いている" },
      { en: "swimming", ja: "泳いでいる" },
      { en: "dancing",  ja: "踊っている" },
      { en: "walking",  ja: "歩いている" },
      { en: "making",   ja: "作っている" },
    ],
    sentences: [
      { ja: "私は今英語を勉強しています。",   tokens: ["I", "am", "studying", "English", "now"] },
      { ja: "彼はサッカーをしています。",     tokens: ["He", "is", "playing", "soccer"] },
      { ja: "彼女は本を読んでいます。",       tokens: ["She", "is", "reading", "a", "book"] },
      { ja: "私は昼ごはんを食べています。",   tokens: ["I", "am", "eating", "lunch"] },
      { ja: "彼らは歌っています。",           tokens: ["They", "are", "singing"] },
      { ja: "私の母は料理をしています。",     tokens: ["My", "mother", "is", "cooking"] },
      { ja: "彼女は今泳いでいます。",         tokens: ["She", "is", "swimming", "now"] },
      { ja: "私は手紙を書いています。",       tokens: ["I", "am", "writing", "a", "letter"] },
      { ja: "彼らは踊っています。",           tokens: ["They", "are", "dancing"] },
      { ja: "私の父は歩いています。",         tokens: ["My", "father", "is", "walking"] },
    ],
  },

  // ============================================================
  {
    id: "u8",
    title: "Unit 8　過去形（played / went / was）",
    words: [
      { en: "yesterday", ja: "昨日" },
      { en: "played",    ja: "した（過去）" },
      { en: "went",      ja: "行った" },
      { en: "ate",       ja: "食べた" },
      { en: "studied",   ja: "勉強した" },
      { en: "was",       ja: "〜だった（I / he）" },
      { en: "were",      ja: "〜だった（you / they）" },
      { en: "saw",       ja: "見た" },
      { en: "enjoyed",   ja: "楽しんだ" },
      { en: "busy",      ja: "忙しい" },
      { en: "watched",   ja: "見た（過去）" },
      { en: "had",       ja: "持っていた" },
      { en: "last",      ja: "この前の" },
      { en: "made",      ja: "作った" },
      { en: "came",      ja: "来た" },
    ],
    sentences: [
      { ja: "私は昨日サッカーをしました。",   tokens: ["I", "played", "soccer", "yesterday"] },
      { ja: "私は昨日公園に行きました。",     tokens: ["I", "went", "to", "the", "park", "yesterday"] },
      { ja: "私は昨日英語を勉強しました。",   tokens: ["I", "studied", "English", "yesterday"] },
      { ja: "私は昨日うれしかったです。",     tokens: ["I", "was", "happy", "yesterday"] },
      { ja: "あなたは昨日忙しかったです。",   tokens: ["You", "were", "busy", "yesterday"] },
      { ja: "私は映画を楽しみました。",       tokens: ["I", "enjoyed", "the", "movie"] },
      { ja: "私は昨日テレビを見ました。",     tokens: ["I", "watched", "TV", "yesterday"] },
      { ja: "私は犬を飼っていました。",       tokens: ["I", "had", "a", "dog"] },
      { ja: "私は先週京都に行きました。",     tokens: ["I", "went", "to", "Kyoto", "last", "week"] },
      { ja: "彼女は昨日忙しかったです。",     tokens: ["She", "was", "busy", "yesterday"] },
    ],
  },

  // ============================================================
  {
    id: "u9",
    title: "Unit 9　命令文・Let's（〜しなさい / 〜しよう）",
    words: [
      { en: "open",    ja: "開ける" },
      { en: "close",   ja: "閉める" },
      { en: "stand",   ja: "立つ" },
      { en: "sit",     ja: "座る" },
      { en: "look",    ja: "目を向ける・見る" },
      { en: "listen",  ja: "聞く" },
      { en: "please",  ja: "どうぞ・ください" },
      { en: "let's",   ja: "〜しよう" },
      { en: "stop",    ja: "止まる・やめる" },
      { en: "come",    ja: "来る" },
      { en: "wait",    ja: "待つ" },
      { en: "careful", ja: "注意して" },
    ],
    sentences: [
      { ja: "立ってください。",       tokens: ["Please", "stand", "up"] },
      { ja: "すわってください。",     tokens: ["Please", "sit", "down"] },
      { ja: "ドアを開けてください。", tokens: ["Please", "open", "the", "door"] },
      { ja: "黒板を見て。",           tokens: ["Look", "at", "the", "blackboard"] },
      { ja: "私の話を聞いて。",       tokens: ["Listen", "to", "me"] },
      { ja: "サッカーをしよう。",     tokens: ["Let's", "play", "soccer"] },
      { ja: "いっしょに歌おう。",     tokens: ["Let's", "sing", "together"] },
      { ja: "気をつけて。",           tokens: ["Be", "careful"] },
    ],
  },

  // ============================================================
  {
    id: "u10",
    title: "Unit 10　前置詞・場所（in / on / There is）",
    words: [
      { en: "in",    ja: "〜の中に" },
      { en: "on",    ja: "〜の上に" },
      { en: "under", ja: "〜の下に" },
      { en: "by",    ja: "〜のそばに" },
      { en: "near",  ja: "〜の近くに" },
      { en: "here",  ja: "ここに" },
      { en: "there", ja: "そこに" },
      { en: "desk",  ja: "机" },
      { en: "room",  ja: "部屋" },
      { en: "table", ja: "テーブル" },
      { en: "wall",  ja: "かべ" },
      { en: "park",  ja: "公園" },
    ],
    sentences: [
      { ja: "ねこは箱の中にいます。",             tokens: ["The", "cat", "is", "in", "the", "box"] },
      { ja: "本は机の上にあります。",             tokens: ["The", "book", "is", "on", "the", "desk"] },
      { ja: "ボールはいすの下にあります。",       tokens: ["The", "ball", "is", "under", "the", "chair"] },
      { ja: "かばんはテーブルのそばにあります。", tokens: ["The", "bag", "is", "by", "the", "table"] },
      { ja: "部屋に犬が1匹います。",             tokens: ["There", "is", "a", "dog", "in", "the", "room"] },
      { ja: "公園に2匹のねこがいます。",         tokens: ["There", "are", "two", "cats", "in", "the", "park"] },
      { ja: "私の家の近くに学校があります。",     tokens: ["There", "is", "a", "school", "near", "my", "house"] },
      { ja: "私はここにいます。",                 tokens: ["I", "am", "here"] },
    ],
  },

  // ============================================================
  {
    id: "u11",
    title: "Unit 11　曜日・月・季節",
    words: [
      { en: "Monday",   ja: "月曜日" },
      { en: "Tuesday",  ja: "火曜日" },
      { en: "Sunday",   ja: "日曜日" },
      { en: "morning",  ja: "朝" },
      { en: "week",     ja: "週" },
      { en: "month",    ja: "月（暦）" },
      { en: "year",     ja: "年" },
      { en: "spring",   ja: "春" },
      { en: "summer",   ja: "夏" },
      { en: "winter",   ja: "冬" },
      { en: "January",  ja: "1月" },
      { en: "December", ja: "12月" },
    ],
    sentences: [
      { ja: "今日は月曜日です。",                 tokens: ["It", "is", "Monday", "today"] },
      { ja: "私は日曜日にサッカーをします。",     tokens: ["I", "play", "soccer", "on", "Sunday"] },
      { ja: "私は毎朝走ります。",                 tokens: ["I", "run", "every", "morning"] },
      { ja: "私は夏が好きです。",                 tokens: ["I", "like", "summer"] },
      { ja: "私の誕生日は12月です。",             tokens: ["My", "birthday", "is", "in", "December"] },
      { ja: "私たちは月曜日に英語を勉強します。", tokens: ["We", "study", "English", "on", "Monday"] },
      { ja: "春は暖かいです。",                   tokens: ["Spring", "is", "warm"] },
      { ja: "冬は寒いです。",                     tokens: ["Winter", "is", "cold"] },
    ],
  },

  // ============================================================
  {
    id: "u12",
    title: "Unit 12　数と年齢（How many / How old）",
    words: [
      { en: "old",     ja: "年をとった・古い" },
      { en: "six",     ja: "6" },
      { en: "seven",   ja: "7" },
      { en: "eight",   ja: "8" },
      { en: "nine",    ja: "9" },
      { en: "ten",     ja: "10" },
      { en: "twelve",  ja: "12" },
      { en: "twenty",  ja: "20" },
      { en: "hundred", ja: "100" },
      { en: "number",  ja: "数" },
      { en: "years",   ja: "年（複数）" },
      { en: "age",     ja: "年齢" },
    ],
    sentences: [
      { ja: "あなたは何冊の本を持っていますか。",   tokens: ["How", "many", "books", "do", "you", "have"] },
      { ja: "私は本を6冊持っています。",           tokens: ["I", "have", "six", "books"] },
      { ja: "あなたは何歳ですか。",                 tokens: ["How", "old", "are", "you"] },
      { ja: "私は12歳です。",                       tokens: ["I", "am", "twelve", "years", "old"] },
      { ja: "私のクラスには30人の生徒がいます。",   tokens: ["There", "are", "thirty", "students", "in", "my", "class"] },
      { ja: "私は7時に起きます。",                 tokens: ["I", "get", "up", "at", "seven"] },
      { ja: "彼は10歳です。",                       tokens: ["He", "is", "ten", "years", "old"] },
      { ja: "りんごがいくつかあります。",           tokens: ["There", "are", "some", "apples"] },
    ],
  },

  // ============================================================
  {
    id: "u13",
    title: "Unit 13　家族と人",
    words: [
      { en: "family",      ja: "家族" },
      { en: "grandmother", ja: "祖母" },
      { en: "grandfather", ja: "祖父" },
      { en: "parents",     ja: "両親" },
      { en: "baby",        ja: "赤ちゃん" },
      { en: "boy",         ja: "男の子" },
      { en: "girl",        ja: "女の子" },
      { en: "people",      ja: "人々" },
      { en: "aunt",        ja: "おば" },
      { en: "uncle",       ja: "おじ" },
      { en: "woman",       ja: "女性" },
      { en: "man",         ja: "男性" },
    ],
    sentences: [
      { ja: "これは私の家族です。",           tokens: ["This", "is", "my", "family"] },
      { ja: "彼は私の祖父です。",             tokens: ["He", "is", "my", "grandfather"] },
      { ja: "彼女は私の祖母です。",           tokens: ["She", "is", "my", "grandmother"] },
      { ja: "あの男の子は私の友達です。",     tokens: ["That", "boy", "is", "my", "friend"] },
      { ja: "あの女の子は私の妹です。",       tokens: ["That", "girl", "is", "my", "sister"] },
      { ja: "私には2人の兄弟がいます。",       tokens: ["I", "have", "two", "brothers"] },
      { ja: "私の両親は親切です。",           tokens: ["My", "parents", "are", "kind"] },
      { ja: "彼らは私のおじとおばです。",     tokens: ["They", "are", "my", "uncle", "and", "aunt"] },
    ],
  },

  // ============================================================
  {
    id: "u14",
    title: "Unit 14　食べ物・飲み物",
    words: [
      { en: "rice",      ja: "ごはん・米" },
      { en: "bread",     ja: "パン" },
      { en: "milk",      ja: "牛乳" },
      { en: "egg",       ja: "卵" },
      { en: "fish",      ja: "魚" },
      { en: "meat",      ja: "肉" },
      { en: "fruit",     ja: "くだもの" },
      { en: "vegetable", ja: "野菜" },
      { en: "tea",       ja: "お茶" },
      { en: "juice",     ja: "ジュース" },
      { en: "cake",      ja: "ケーキ" },
      { en: "lunch",     ja: "昼食" },
    ],
    sentences: [
      { ja: "私は朝ごはんにパンを食べます。",     tokens: ["I", "eat", "bread", "for", "breakfast"] },
      { ja: "私は牛乳を飲みます。",               tokens: ["I", "drink", "milk"] },
      { ja: "私は魚が好きです。",                 tokens: ["I", "like", "fish"] },
      { ja: "私はくだものを食べたいです。",       tokens: ["I", "want", "to", "eat", "fruit"] },
      { ja: "私はケーキが大好きです。",           tokens: ["I", "love", "cake"] },
      { ja: "私はお昼にごはんを食べます。",       tokens: ["I", "eat", "rice", "for", "lunch"] },
      { ja: "私はお茶を飲みません。",             tokens: ["I", "do", "not", "drink", "tea"] },
      { ja: "私は野菜が好きです。",               tokens: ["I", "like", "vegetables"] },
    ],
  },

  // ============================================================
  {
    id: "u15",
    title: "Unit 15　様子・気持ち（形容詞）",
    words: [
      { en: "big",       ja: "大きい" },
      { en: "small",     ja: "小さい" },
      { en: "long",      ja: "長い" },
      { en: "short",     ja: "短い" },
      { en: "new",       ja: "新しい" },
      { en: "cute",      ja: "かわいい" },
      { en: "cold",      ja: "寒い・冷たい" },
      { en: "hot",       ja: "暑い・熱い" },
      { en: "sad",       ja: "悲しい" },
      { en: "kind",      ja: "親切な" },
      { en: "beautiful", ja: "美しい" },
      { en: "tired",     ja: "疲れた" },
    ],
    sentences: [
      { ja: "この犬は大きいです。",           tokens: ["This", "dog", "is", "big"] },
      { ja: "あのねこは小さいです。",         tokens: ["That", "cat", "is", "small"] },
      { ja: "私は新しい自転車を持っています。", tokens: ["I", "have", "a", "new", "bike"] },
      { ja: "このケーキはとてもおいしいです。", tokens: ["This", "cake", "is", "very", "good"] },
      { ja: "私は今日とても疲れています。",     tokens: ["I", "am", "very", "tired", "today"] },
      { ja: "彼女はとても親切です。",         tokens: ["She", "is", "very", "kind"] },
      { ja: "その花は美しいです。",           tokens: ["The", "flower", "is", "beautiful"] },
      { ja: "私のねこはかわいいです。",       tokens: ["My", "cat", "is", "cute"] },
    ],
  },

  // ============================================================
  {
    id: "u16",
    title: "Unit 16　学校・身の回りのもの",
    words: [
      { en: "school",     ja: "学校" },
      { en: "classroom",  ja: "教室" },
      { en: "pencil",     ja: "えんぴつ" },
      { en: "eraser",     ja: "消しゴム" },
      { en: "notebook",   ja: "ノート" },
      { en: "ruler",      ja: "じょうぎ" },
      { en: "dictionary", ja: "辞書" },
      { en: "computer",   ja: "コンピューター" },
      { en: "clock",      ja: "時計" },
      { en: "window",     ja: "窓" },
      { en: "chair",      ja: "いす" },
      { en: "blackboard", ja: "黒板" },
    ],
    sentences: [
      { ja: "これは私の教室です。",                 tokens: ["This", "is", "my", "classroom"] },
      { ja: "私はえんぴつを3本持っています。",       tokens: ["I", "have", "three", "pencils"] },
      { ja: "これはあなたの辞書ですか。",           tokens: ["Is", "this", "your", "dictionary"] },
      { ja: "私の学校は大きいです。",               tokens: ["My", "school", "is", "big"] },
      { ja: "私は新しいコンピューターがほしいです。", tokens: ["I", "want", "a", "new", "computer"] },
      { ja: "時計はかべにあります。",               tokens: ["The", "clock", "is", "on", "the", "wall"] },
      { ja: "いすに座ってください。",               tokens: ["Please", "sit", "on", "the", "chair"] },
      { ja: "窓を開けてください。",                 tokens: ["Please", "open", "the", "window"] },
    ],
  },
];

// むずかしいモード用のダミー単語プール（語順とは関係ない おとり）
const DUMMY_POOL = ["he", "she", "is", "the", "a", "my", "your", "in", "on", "and", "not", "very", "do", "they"];

// ============================================================
//  日本一周の旅（じてんしゃで にっぽんいっしゅう）
// ============================================================
// 正解するたびに距離(km)が進み、各県に到着すると紹介カードが見られる。
// spots は旅の順番。先頭(三重・亀山)がスタート＝ゴール。
//   pref: 県名 / full: 表示名 / city: 代表地 / emoji: その県の絵文字
//   x,y : 地図上の位置（viewBox 0 0 86 100 上の座標）
//   intro: 到着すると見られる ごほうび知識（日本語）
// km（累積距離）と goalKm は app.js が segKm から自動計算する。
const JOURNEY = {
  kmPerCorrect: 2,  // 1問正解で進む距離
  segKm: 105,       // 県と県のあいだの距離（合計約5000kmで半年ペース）
  arriveCoin: 10,   // 県に到着したときのコインボーナス
  spots: [
    { pref: "三重",   full: "三重県",   city: "亀山",   emoji: "🏯", x: 52, y: 64, intro: "ここが出発の地！松阪牛やお伊勢さん（伊勢神宮）、忍者の里で有名だよ。" },
    { pref: "愛知",   full: "愛知県",   city: "名古屋", emoji: "🏭", x: 56, y: 62, intro: "大きな町・名古屋がある県。みそカツやひつまぶし、車づくりがさかんだよ。" },
    { pref: "静岡",   full: "静岡県",   city: "静岡",   emoji: "🗻", x: 63, y: 62, intro: "富士山とお茶の名産地。うなぎやみかんもおいしいよ。" },
    { pref: "山梨",   full: "山梨県",   city: "甲府",   emoji: "🍇", x: 65, y: 58, intro: "ぶどうとももの王国。富士山の北がわにある内陸の県だよ。" },
    { pref: "神奈川", full: "神奈川県", city: "横浜",   emoji: "⚓", x: 70, y: 61, intro: "横浜の中華街やみなとが有名。鎌倉の大仏もあるよ。" },
    { pref: "東京",   full: "東京都",   city: "東京",   emoji: "🗼", x: 72, y: 57, intro: "日本の首都。スカイツリーや東京タワー、人がいっぱい！" },
    { pref: "千葉",   full: "千葉県",   city: "千葉",   emoji: "🎢", x: 79, y: 57, intro: "大きなテーマパークと広い海。らっかせいが名産だよ。" },
    { pref: "埼玉",   full: "埼玉県",   city: "さいたま", emoji: "🌾", x: 68, y: 54, intro: "東京のおとなりの内陸県。草加せんべいや川越の古い町なみが有名。" },
    { pref: "群馬",   full: "群馬県",   city: "前橋",   emoji: "♨️", x: 64, y: 51, intro: "草津など温泉がいっぱいの内陸県。こんにゃくの名産地だよ。" },
    { pref: "栃木",   full: "栃木県",   city: "宇都宮", emoji: "🍓", x: 70, y: 50, intro: "あまいいちご（とちおとめ）と日光の社寺で有名な内陸県。" },
    { pref: "茨城",   full: "茨城県",   city: "水戸",   emoji: "🍈", x: 78, y: 52, intro: "なっとうとメロンが名産。大きな牛久大仏もあるよ。" },
    { pref: "福島",   full: "福島県",   city: "福島",   emoji: "🍑", x: 68, y: 46, intro: "ももがおいしい。会津の赤べことお城（鶴ヶ城）が有名だよ。" },
    { pref: "宮城",   full: "宮城県",   city: "仙台",   emoji: "🐂", x: 73, y: 40, intro: "仙台の牛タンとずんだもち。七夕まつりがきれいだよ。" },
    { pref: "岩手",   full: "岩手県",   city: "盛岡",   emoji: "🍜", x: 74, y: 33, intro: "わんこそばが名物。広い県で、かっぱ伝説の遠野もあるよ。" },
    { pref: "青森",   full: "青森県",   city: "青森",   emoji: "🍎", x: 70, y: 27, intro: "りんごの生産が日本一！ねぶた祭りが大はくりょく。" },
    { pref: "北海道", full: "北海道",   city: "札幌",   emoji: "🐄", x: 73, y: 13, intro: "日本でいちばん大きい！雪まつり・カニ・牛乳・じゃがいもで有名。" },
    { pref: "秋田",   full: "秋田県",   city: "秋田",   emoji: "🐕", x: 61, y: 32, intro: "あきた犬と、なまはげが有名。お米もおいしいよ。" },
    { pref: "山形",   full: "山形県",   city: "山形",   emoji: "🍒", x: 61, y: 40, intro: "さくらんぼが日本一！べにばなとおいしいお米のふるさと。" },
    { pref: "新潟",   full: "新潟県",   city: "新潟",   emoji: "🍚", x: 59, y: 45, intro: "お米（コシヒカリ）とおもちの名産地。冬は雪がたくさんふるよ。" },
    { pref: "長野",   full: "長野県",   city: "長野",   emoji: "🍎", x: 60, y: 55, intro: "山にかこまれた内陸県。そばやりんご、スキーで有名だよ。" },
    { pref: "富山",   full: "富山県",   city: "富山",   emoji: "💊", x: 54, y: 49, intro: "立山のけしきとホタルイカ。くすりづくりでも有名だよ。" },
    { pref: "石川",   full: "石川県",   city: "金沢",   emoji: "🏮", x: 50, y: 47, intro: "金沢の兼六園と金ぱく。九谷焼やおすしがおいしいよ。" },
    { pref: "福井",   full: "福井県",   city: "福井",   emoji: "🦕", x: 49, y: 54, intro: "きょうりゅうの化石で有名。めがねづくりとカニも名物だよ。" },
    { pref: "岐阜",   full: "岐阜県",   city: "岐阜",   emoji: "🏠", x: 54, y: 57, intro: "白川郷のかやぶき屋根が世界遺産。山おくの内陸県だよ。" },
    { pref: "滋賀",   full: "滋賀県",   city: "大津",   emoji: "🌊", x: 50, y: 60, intro: "日本でいちばん大きい湖・びわ湖がある内陸県だよ。" },
    { pref: "京都",   full: "京都府",   city: "京都",   emoji: "⛩️", x: 47, y: 60, intro: "古いお寺と神社がいっぱいの昔のみやこ。きよみず寺が有名。" },
    { pref: "大阪",   full: "大阪府",   city: "大阪",   emoji: "🐙", x: 46, y: 64, intro: "たこ焼き・お好み焼きの食いだおれの町。通天閣が有名だよ。" },
    { pref: "奈良",   full: "奈良県",   city: "奈良",   emoji: "🦌", x: 50, y: 66, intro: "大きな大仏と、人になれたシカがいる内陸県だよ。" },
    { pref: "和歌山", full: "和歌山県", city: "和歌山", emoji: "🍊", x: 47, y: 70, intro: "みかんとうめぼしの名産地。高野山やパンダで有名だよ。" },
    { pref: "兵庫",   full: "兵庫県",   city: "神戸",   emoji: "🌉", x: 43, y: 61, intro: "神戸の港と長い橋（明石海峡大橋）。神戸牛がおいしいよ。" },
    { pref: "岡山",   full: "岡山県",   city: "岡山",   emoji: "🍑", x: 39, y: 62, intro: "ももたろうのふるさと。あまいマスカットと白いお城。" },
    { pref: "鳥取",   full: "鳥取県",   city: "鳥取",   emoji: "🐪", x: 39, y: 56, intro: "日本一大きなすな丘（鳥取砂丘）。ラクダにも乗れるよ。" },
    { pref: "島根",   full: "島根県",   city: "松江",   emoji: "🏯", x: 32, y: 58, intro: "縁むすびの出雲大社。古いお城やたたら製鉄で有名だよ。" },
    { pref: "広島",   full: "広島県",   city: "広島",   emoji: "⛩️", x: 33, y: 63, intro: "海にうかぶ赤い鳥居（厳島神社）とお好み焼き、かきが名物。" },
    { pref: "山口",   full: "山口県",   city: "山口",   emoji: "🐡", x: 26, y: 63, intro: "ふぐ料理で有名。きれいな石の橋（錦帯橋）もあるよ。" },
    { pref: "香川",   full: "香川県",   city: "高松",   emoji: "🍜", x: 38, y: 68, intro: "さぬきうどんの本場！小さいけどうどん日本一の県だよ。" },
    { pref: "徳島",   full: "徳島県",   city: "徳島",   emoji: "💃", x: 41, y: 71, intro: "夏のあわおどりが大にぎわい。うずしおとすだちが名物。" },
    { pref: "高知",   full: "高知県",   city: "高知",   emoji: "🐟", x: 35, y: 73, intro: "かつおのたたきが名物。さかもと龍馬のふるさとだよ。" },
    { pref: "愛媛",   full: "愛媛県",   city: "松山",   emoji: "🍊", x: 29, y: 70, intro: "みかん王国。道後温泉という古い温泉が有名だよ。" },
    { pref: "福岡",   full: "福岡県",   city: "福岡",   emoji: "🍢", x: 22, y: 67, intro: "とんこつラーメンと屋台。明太子（めんたいこ）も名物だよ。" },
    { pref: "佐賀",   full: "佐賀県",   city: "佐賀",   emoji: "🍵", x: 18, y: 68, intro: "焼きもの（有田焼）とおいしいお茶・のりで有名だよ。" },
    { pref: "長崎",   full: "長崎県",   city: "長崎",   emoji: "🚢", x: 14, y: 71, intro: "海と教会の町。カステラやちゃんぽんがおいしいよ。" },
    { pref: "熊本",   full: "熊本県",   city: "熊本",   emoji: "🐻", x: 20, y: 73, intro: "ゆるキャラのくまモンと大きな火山（阿蘇山）で有名。" },
    { pref: "大分",   full: "大分県",   city: "大分",   emoji: "♨️", x: 25, y: 70, intro: "別府や湯布院など、日本一の温泉県だよ。" },
    { pref: "宮崎",   full: "宮崎県",   city: "宮崎",   emoji: "🥭", x: 23, y: 77, intro: "南国のフルーツとマンゴー。チキン南蛮やサーフィンが名物。" },
    { pref: "鹿児島", full: "鹿児島県", city: "鹿児島", emoji: "🌋", x: 18, y: 79, intro: "けむりをあげる桜島という火山。さつまいもと黒ぶたが名物。" },
    { pref: "沖縄",   full: "沖縄県",   city: "那覇",   emoji: "🌺", x: 8,  y: 92, intro: "あたたかい南の島。青い海とシーサー、ゴーヤーが有名だよ。" },
  ],
};

// ============================================================
//  ご当地名物（コインで買って図鑑に集める）
// ============================================================
// 県に到着すると、その県の名物をコインで買えるようになる。
//   name: 名前 / emoji: 絵文字 / price: コイン / desc: 説明文（ごほうび知識）
// id は app.js が「県名#番号」で自動付与する。
const PREF_GOODS = {
  "三重":   [ { name: "松阪牛",       emoji: "🥩", price: 55, desc: "日本でも有名な高級な牛肉。口の中でとろけるおいしさだよ。" },
              { name: "赤福",         emoji: "🍡", price: 25, desc: "伊勢の名物。やわらかいおもちにあんこをのせた和菓子。" },
              { name: "伊勢えび",     emoji: "🦞", price: 45, desc: "伊勢の海でとれる、大きくて立派なえび。" } ],
  "愛知":   [ { name: "みそカツ",     emoji: "🍖", price: 30, desc: "赤みそのたれをかけたとんかつ。名古屋めしの王さま。" },
              { name: "ひつまぶし",   emoji: "🍱", price: 50, desc: "うなぎのどんぶり。3通りの食べ方で楽しむよ。" },
              { name: "エビフライ",   emoji: "🍤", price: 30, desc: "名古屋名物の大きなエビフライ。" } ],
  "静岡":   [ { name: "静岡茶",       emoji: "🍵", price: 20, desc: "生産量が日本トップクラスのおいしいお茶。" },
              { name: "浜名湖うなぎ", emoji: "🐟", price: 45, desc: "浜名湖で育つうなぎが有名だよ。" },
              { name: "みかん",       emoji: "🍊", price: 20, desc: "あたたかい気候で育つ、あまいみかん。" } ],
  "山梨":   [ { name: "ぶどう",       emoji: "🍇", price: 30, desc: "日本でもトップクラスのぶどうの産地。" },
              { name: "もも",         emoji: "🍑", price: 30, desc: "あまくてジューシーな山梨のもも。" },
              { name: "ほうとう",     emoji: "🍲", price: 25, desc: "野菜たっぷりの、太いめんのなべ料理。" } ],
  "神奈川": [ { name: "シウマイ",     emoji: "🥟", price: 25, desc: "横浜中華街でおなじみの名物。" },
              { name: "大仏プリン",   emoji: "🍮", price: 20, desc: "鎌倉の大仏にちなんだかわいいプリン。" },
              { name: "家系ラーメン", emoji: "🍜", price: 30, desc: "こってりスープの横浜うまれのラーメン。" } ],
  "東京":   [ { name: "もんじゃ",     emoji: "🍳", price: 25, desc: "鉄板で焼いて食べる下町の味。" },
              { name: "雷おこし",     emoji: "🍘", price: 15, desc: "浅草の昔ながらのおかし。" },
              { name: "東京ばな奈",   emoji: "🍌", price: 25, desc: "バナナのクリームが入った定番おみやげ。" } ],
  "千葉":   [ { name: "らっかせい",   emoji: "🥜", price: 20, desc: "全国一の生産量をほこるピーナッツ。" },
              { name: "なめろう",     emoji: "🐟", price: 30, desc: "あじなどをたたいて作る漁師めし。" },
              { name: "びわ",         emoji: "🍈", price: 25, desc: "あまくてジューシーな初夏のくだもの。" } ],
  "埼玉":   [ { name: "草加せんべい", emoji: "🍘", price: 15, desc: "かたく焼いたしょうゆせんべい。" },
              { name: "十万石まんじゅう", emoji: "🍡", price: 20, desc: "埼玉で有名な、ふんわり和菓子。" },
              { name: "川越うなぎ",   emoji: "🐟", price: 40, desc: "小江戸・川越のうなぎが名物。" } ],
  "群馬":   [ { name: "こんにゃく",   emoji: "🟤", price: 15, desc: "全国一の生産地。ヘルシーな食べもの。" },
              { name: "焼きまんじゅう", emoji: "🍢", price: 20, desc: "あまいみそだれをぬった群馬名物。" },
              { name: "下仁田ねぎ",   emoji: "🧅", price: 25, desc: "太くてあまい、なべにぴったりのねぎ。" } ],
  "栃木":   [ { name: "とちおとめ",   emoji: "🍓", price: 30, desc: "生産量トップクラスのあまいいちご。" },
              { name: "宇都宮餃子",   emoji: "🥟", price: 25, desc: "宇都宮はぎょうざの町として有名。" },
              { name: "かんぴょう",   emoji: "🍱", price: 20, desc: "ゆうがおから作る、まきずしの具。" } ],
  "茨城":   [ { name: "水戸納豆",     emoji: "🫘", price: 15, desc: "水戸の納豆が全国的に有名。" },
              { name: "メロン",       emoji: "🍈", price: 40, desc: "生産量日本一のあまいメロン。" },
              { name: "あんこう鍋",   emoji: "🍲", price: 45, desc: "冬の名物のあったかいなべ料理。" } ],
  "福島":   [ { name: "あかべこ",     emoji: "🐂", price: 20, desc: "首をふる赤い牛の郷土玩具。" },
              { name: "喜多方ラーメン", emoji: "🍜", price: 30, desc: "あっさりスープのご当地ラーメン。" },
              { name: "もも",         emoji: "🍑", price: 30, desc: "あまくて大きい福島のもも。" } ],
  "宮城":   [ { name: "牛タン",       emoji: "🥩", price: 40, desc: "仙台名物の、あつ切り牛タン焼き。" },
              { name: "ずんだもち",   emoji: "🍡", price: 25, desc: "えだまめのあまいあんをのせたおもち。" },
              { name: "ささかまぼこ", emoji: "🐟", price: 20, desc: "ささの葉の形をしたかまぼこ。" } ],
  "岩手":   [ { name: "わんこそば",   emoji: "🍜", price: 30, desc: "小さなわんで何ばいも食べる名物。" },
              { name: "前沢牛",       emoji: "🥩", price: 55, desc: "やわらかくて有名な高級和牛。" },
              { name: "南部せんべい", emoji: "🍘", price: 15, desc: "パリッとした素朴なせんべい。" } ],
  "青森":   [ { name: "りんご",       emoji: "🍎", price: 25, desc: "生産量日本一。みつたっぷり。" },
              { name: "せんべい汁",   emoji: "🍲", price: 25, desc: "せんべいを入れたあったかい汁もの。" },
              { name: "にんにく",     emoji: "🧄", price: 20, desc: "田子町のにんにくが有名だよ。" } ],
  "北海道": [ { name: "カニ",         emoji: "🦀", price: 55, desc: "大きくて身がぎっしりのカニ。" },
              { name: "ジンギスカン", emoji: "🐑", price: 40, desc: "羊の肉を焼いて食べる名物料理。" },
              { name: "夕張メロン",   emoji: "🍈", price: 45, desc: "あまくて大人気のオレンジ色のメロン。" },
              { name: "ソフトクリーム", emoji: "🍦", price: 20, desc: "牛乳たっぷりの、こいソフトクリーム。" } ],
  "秋田":   [ { name: "きりたんぽ",   emoji: "🍢", price: 30, desc: "つぶしたごはんを棒にまいた、なべの具。" },
              { name: "あきたこまち", emoji: "🍚", price: 25, desc: "つやつやでおいしいお米。" },
              { name: "いぶりがっこ", emoji: "🥒", price: 20, desc: "けむりでいぶしたたくあん。" } ],
  "山形":   [ { name: "さくらんぼ",   emoji: "🍒", price: 40, desc: "生産量日本一。赤くてあまいくだもの。" },
              { name: "米沢牛",       emoji: "🥩", price: 55, desc: "口の中でとろける高級和牛。" },
              { name: "いも煮",       emoji: "🍲", price: 25, desc: "里いもと肉のなべ料理。秋の楽しみ。" } ],
  "新潟":   [ { name: "コシヒカリ",   emoji: "🍚", price: 30, desc: "日本一おいしいと言われるお米。" },
              { name: "へぎそば",     emoji: "🍜", price: 25, desc: "つるつるののどごしのおそば。" },
              { name: "笹だんご",     emoji: "🍡", price: 20, desc: "よもぎだんごをささでつつんだおかし。" } ],
  "長野":   [ { name: "信州そば",     emoji: "🍜", price: 25, desc: "すずしい気候で育つそばが有名。" },
              { name: "りんご",       emoji: "🍎", price: 25, desc: "あまくてシャキッとしたりんご。" },
              { name: "おやき",       emoji: "🥟", price: 20, desc: "野菜などを生地でつつんで焼いたもの。" } ],
  "富山":   [ { name: "ホタルイカ",   emoji: "🦑", price: 35, desc: "青く光る小さなイカ。春の名物。" },
              { name: "ますずし",     emoji: "🍣", price: 30, desc: "ますをのせた、まるいおすし。" },
              { name: "白えび",       emoji: "🦐", price: 40, desc: "とうめいであまい、小さなえび。" } ],
  "石川":   [ { name: "金ぱくソフト", emoji: "🍦", price: 35, desc: "金ぱくをのせた、ごうかなソフトクリーム。" },
              { name: "のどぐろ",     emoji: "🐟", price: 50, desc: "あぶらがのった高級な魚。" },
              { name: "九谷焼",       emoji: "🍶", price: 30, desc: "色あざやかな、うつくしい焼きもの。" } ],
  "福井":   [ { name: "越前がに",     emoji: "🦀", price: 55, desc: "福井のブランドガニ。" },
              { name: "ソースカツ丼", emoji: "🍱", price: 30, desc: "ソースをくぐらせたカツのどんぶり。" },
              { name: "めがね",       emoji: "👓", price: 25, desc: "鯖江はめがねづくりが日本一。" } ],
  "岐阜":   [ { name: "飛騨牛",       emoji: "🥩", price: 55, desc: "やわらかくて有名な高級和牛。" },
              { name: "五平もち",     emoji: "🍡", price: 25, desc: "つぶしたごはんをたれで焼いたもの。" },
              { name: "朴葉みそ",     emoji: "🍲", price: 25, desc: "葉の上でみそを焼く郷土料理。" } ],
  "滋賀":   [ { name: "近江牛",       emoji: "🥩", price: 55, desc: "日本三大和牛のひとつ。" },
              { name: "ふなずし",     emoji: "🐟", price: 35, desc: "古くから伝わるなれずし。" },
              { name: "赤こんにゃく", emoji: "🟥", price: 20, desc: "赤い色のめずらしいこんにゃく。" } ],
  "京都":   [ { name: "八ツ橋",       emoji: "🍡", price: 25, desc: "ニッキの香りの和菓子。" },
              { name: "抹茶パフェ",   emoji: "🍨", price: 35, desc: "宇治抹茶のあまいパフェ。" },
              { name: "ゆば",         emoji: "🍢", price: 30, desc: "大豆から作る上品な食べもの。" } ],
  "大阪":   [ { name: "たこ焼き",     emoji: "🐙", price: 20, desc: "大阪の定番。中にタコが入っているよ。" },
              { name: "お好み焼き",   emoji: "🍳", price: 25, desc: "鉄板で焼く粉もの料理。" },
              { name: "串カツ",       emoji: "🍢", price: 25, desc: "あげたて。ソースの二度づけはきんし！" } ],
  "奈良":   [ { name: "柿の葉ずし",   emoji: "🍣", price: 25, desc: "柿の葉でつつんだおすし。" },
              { name: "奈良漬け",     emoji: "🥒", price: 20, desc: "うりなどをつけこんだつけもの。" },
              { name: "大仏プリン",   emoji: "🍮", price: 20, desc: "奈良の大仏にちなんだプリン。" } ],
  "和歌山": [ { name: "みかん",       emoji: "🍊", price: 25, desc: "生産量日本一のあまいみかん。" },
              { name: "梅干し",       emoji: "🟣", price: 20, desc: "南高梅で作る、すっぱいうめぼし。" },
              { name: "和歌山ラーメン", emoji: "🍜", price: 30, desc: "とんこつしょうゆのご当地ラーメン。" } ],
  "兵庫":   [ { name: "神戸牛",       emoji: "🥩", price: 55, desc: "世界的に有名な高級和牛。" },
              { name: "明石焼き",     emoji: "🍳", price: 25, desc: "だしにつけて食べる、たまご焼き。" },
              { name: "いかなごのくぎ煮", emoji: "🐟", price: 25, desc: "春につくる、あまからいつくだ煮。" } ],
  "岡山":   [ { name: "マスカット",   emoji: "🍇", price: 45, desc: "あまくて高級なみどりのぶどう。" },
              { name: "きびだんご",   emoji: "🍡", price: 15, desc: "ももたろうでおなじみのおだんご。" },
              { name: "ばらずし",     emoji: "🍣", price: 30, desc: "具だくさんの、はなやかなちらしずし。" } ],
  "鳥取":   [ { name: "二十世紀梨",   emoji: "🍐", price: 30, desc: "みずみずしい、あおい梨。" },
              { name: "松葉がに",     emoji: "🦀", price: 50, desc: "冬の名物のカニ。" },
              { name: "砂丘らっきょう", emoji: "🧅", price: 20, desc: "砂丘で育つ、シャキシャキのらっきょう。" } ],
  "島根":   [ { name: "出雲そば",     emoji: "🍜", price: 25, desc: "わんに分けて食べる、こい色のそば。" },
              { name: "しじみ",       emoji: "🐚", price: 25, desc: "宍道湖でとれるしじみ。" },
              { name: "ぜんざい",     emoji: "🍡", price: 20, desc: "出雲がぜんざい発祥といわれているよ。" } ],
  "広島":   [ { name: "広島お好み焼き", emoji: "🍳", price: 30, desc: "そばが入った、かさねて焼くお好み焼き。" },
              { name: "かき",         emoji: "🦪", price: 40, desc: "育てるかきの生産が日本一。" },
              { name: "もみじまんじゅう", emoji: "🍁", price: 15, desc: "もみじの形をした和菓子。" } ],
  "山口":   [ { name: "ふぐ",         emoji: "🐡", price: 55, desc: "高級魚のふぐ料理が名物。" },
              { name: "瓦そば",       emoji: "🍜", price: 30, desc: "あつい瓦の上で焼くおそば。" },
              { name: "夏みかん",     emoji: "🍊", price: 20, desc: "さわやかなすっぱさのみかん。" } ],
  "香川":   [ { name: "さぬきうどん", emoji: "🍜", price: 20, desc: "コシの強いうどん。日本一の本場だよ。" },
              { name: "おいり",       emoji: "🍬", price: 15, desc: "カラフルでまるい、かわいいおかし。" },
              { name: "骨付鳥",       emoji: "🍗", price: 35, desc: "スパイシーに焼いたとり肉。" } ],
  "徳島":   [ { name: "すだち",       emoji: "🟢", price: 15, desc: "さわやかな香りのかんきつ。" },
              { name: "鳴門金時",     emoji: "🍠", price: 25, desc: "ほくほくであまいさつまいも。" },
              { name: "徳島ラーメン", emoji: "🍜", price: 30, desc: "こい色のスープのご当地ラーメン。" } ],
  "高知":   [ { name: "かつおのたたき", emoji: "🐟", price: 40, desc: "わらの火で表面を焼いたかつお。" },
              { name: "ゆず",         emoji: "🍋", price: 20, desc: "香りのよいかんきつ。" },
              { name: "アイスクリン", emoji: "🍦", price: 15, desc: "昔ながらの、さっぱりしたアイス。" } ],
  "愛媛":   [ { name: "みかん",       emoji: "🍊", price: 25, desc: "生産量トップクラスのみかん。" },
              { name: "じゃこ天",     emoji: "🐟", price: 20, desc: "魚のすり身をあげたもの。" },
              { name: "ポンジュース", emoji: "🧃", price: 15, desc: "みかんジュースの定番。" } ],
  "福岡":   [ { name: "とんこつラーメン", emoji: "🍜", price: 30, desc: "白いスープの博多ラーメン。" },
              { name: "明太子",       emoji: "🌶️", price: 35, desc: "ピリ辛のたらこ。ごはんにぴったり。" },
              { name: "もつ鍋",       emoji: "🍲", price: 40, desc: "もつと野菜のあったかいなべ。" } ],
  "佐賀":   [ { name: "有田焼",       emoji: "🍶", price: 35, desc: "白くてうつくしい焼きもの。" },
              { name: "佐賀牛",       emoji: "🥩", price: 55, desc: "きめ細かい、とろける高級和牛。" },
              { name: "むつごろう",   emoji: "🐟", price: 25, desc: "有明海にすむ、めずらしい魚。" } ],
  "長崎":   [ { name: "カステラ",     emoji: "🍰", price: 25, desc: "ふんわりあまい焼きがし。" },
              { name: "ちゃんぽん",   emoji: "🍜", price: 30, desc: "具だくさんのめん料理。" },
              { name: "びわ",         emoji: "🍈", price: 25, desc: "あまくてやさしい味のくだもの。" } ],
  "熊本":   [ { name: "馬刺し",       emoji: "🐴", price: 45, desc: "新せんな馬の刺身。熊本の名物。" },
              { name: "からし蓮根",   emoji: "🪷", price: 25, desc: "れんこんにからしみそをつめてあげたもの。" },
              { name: "いきなり団子", emoji: "🍡", price: 20, desc: "さつまいもとあんこ入りのおだんご。" } ],
  "大分":   [ { name: "とり天",       emoji: "🍗", price: 30, desc: "とり肉の天ぷら。大分のソウルフード。" },
              { name: "かぼす",       emoji: "🟢", price: 15, desc: "さわやかな香りのかんきつ。" },
              { name: "やせうま",     emoji: "🍝", price: 20, desc: "きなこをかけた、もちもちのおやつ。" } ],
  "宮崎":   [ { name: "マンゴー",     emoji: "🥭", price: 50, desc: "とろけるあまさの高級マンゴー。" },
              { name: "チキン南蛮",   emoji: "🍗", price: 35, desc: "あまずっぱいタレととろりのソース。" },
              { name: "冷や汁",       emoji: "🍲", price: 25, desc: "つめたいみそ汁をごはんにかけて食べる。" } ],
  "鹿児島": [ { name: "黒豚",         emoji: "🐖", price: 45, desc: "やわらかくてあまい、黒ぶたの肉。" },
              { name: "さつまあげ",   emoji: "🐟", price: 20, desc: "魚のすり身をあげたもの。" },
              { name: "しろくま",     emoji: "🍧", price: 30, desc: "フルーツたっぷりのかき氷。" } ],
  "沖縄":   [ { name: "ゴーヤーチャンプルー", emoji: "🥒", price: 25, desc: "ゴーヤと豆腐のいためもの。" },
              { name: "ちんすこう",   emoji: "🍪", price: 15, desc: "サクサクの伝統的なおかし。" },
              { name: "サーターアンダギー", emoji: "🧆", price: 20, desc: "あまくてまるい、あげドーナツ。" },
              { name: "紅いも",       emoji: "🍠", price: 25, desc: "あざやかなむらさき色のおいも。" } ],
};
