// ===== 中1 えいごドリル：問題データ =====
// 光村「Here We Go!」の単元構成に寄せた中1標準のオリジナル問題。
// 教科書と完全一致ではありません。あとから自由に追加・差し替えできます。
//
// words: { en:英単語, ja:日本語 }
// sentences: { ja:日本語文, tokens:[正しい語順の英単語] }
//   ※ ピリオドや「？」は自動表示。tokens には単語だけを入れる。先頭は大文字で。

const UNITS = [
  // ============================================================
  {
    id: "u1",
    title: "Unit 1　自己紹介（be動詞 am / are）",
    words: [
      { en: "I",       ja: "私は" },
      { en: "you",     ja: "あなたは" },
      { en: "am",      ja: "〜です（I のとき）" },
      { en: "are",     ja: "〜です（you のとき）" },
      { en: "name",    ja: "名前" },
      { en: "friend",  ja: "友達" },
      { en: "student", ja: "生徒・学生" },
      { en: "happy",   ja: "うれしい" },
      { en: "from",    ja: "〜出身で" },
      { en: "nice",    ja: "素敵な・良い" },
      { en: "this",    ja: "これは" },
      { en: "is",      ja: "〜です（he / it のとき）" },
      { en: "hungry",  ja: "おなかがすいた" },
      { en: "fine",    ja: "元気な" },
      { en: "great",   ja: "すばらしい" },
    ],
    sentences: [
      { ja: "私は学生です。",         tokens: ["I", "am", "a", "student"] },
      { ja: "あなたは私の友達です。",   tokens: ["You", "are", "my", "friend"] },
      { ja: "私はうれしいです。",       tokens: ["I", "am", "happy"] },
      { ja: "私はケンです。",          tokens: ["I", "am", "Ken"] },
      { ja: "あなたは素敵です。",       tokens: ["You", "are", "nice"] },
      { ja: "私は大阪出身です。",       tokens: ["I", "am", "from", "Osaka"] },
      { ja: "これはペンです。",         tokens: ["This", "is", "a", "pen"] },
      { ja: "私は元気です。",          tokens: ["I", "am", "fine"] },
      { ja: "私はおなかがすいています。", tokens: ["I", "am", "hungry"] },
      { ja: "あなたはすばらしいです。",  tokens: ["You", "are", "great"] },
    ],
  },

  // ============================================================
  {
    id: "u2",
    title: "Unit 2　一般動詞（like / play / have）",
    words: [
      { en: "like",   ja: "好きだ" },
      { en: "play",   ja: "（スポーツ・楽器を）する" },
      { en: "have",   ja: "持っている・飼っている" },
      { en: "want",   ja: "ほしい" },
      { en: "eat",    ja: "食べる" },
      { en: "study",  ja: "勉強する" },
      { en: "know",   ja: "知っている" },
      { en: "go",     ja: "行く" },
      { en: "speak",  ja: "話す" },
      { en: "music",  ja: "音楽" },
      { en: "drink",  ja: "飲む" },
      { en: "use",    ja: "使う" },
      { en: "help",   ja: "助ける" },
      { en: "make",   ja: "作る" },
      { en: "tennis", ja: "テニス" },
    ],
    sentences: [
      { ja: "私はサッカーが好きです。",       tokens: ["I", "like", "soccer"] },
      { ja: "私は毎日英語を勉強します。",     tokens: ["I", "study", "English", "every", "day"] },
      { ja: "私はギターを弾きます。",         tokens: ["I", "play", "the", "guitar"] },
      { ja: "私は犬を飼っています。",         tokens: ["I", "have", "a", "dog"] },
      { ja: "私は音楽が好きです。",           tokens: ["I", "like", "music"] },
      { ja: "私は朝ごはんを食べます。",       tokens: ["I", "eat", "breakfast"] },
      { ja: "私は水を飲みます。",             tokens: ["I", "drink", "water"] },
      { ja: "私はテニスをします。",           tokens: ["I", "play", "tennis"] },
      { ja: "私は数学が好きです。",           tokens: ["I", "like", "math"] },
      { ja: "私は新しいかばんがほしいです。", tokens: ["I", "want", "a", "new", "bag"] },
    ],
  },

  // ============================================================
  {
    id: "u3",
    title: "Unit 3　名詞の複数形と数",
    words: [
      { en: "many",   ja: "たくさんの" },
      { en: "some",   ja: "いくつかの" },
      { en: "book",   ja: "本" },
      { en: "apple",  ja: "りんご" },
      { en: "pen",    ja: "ペン" },
      { en: "two",    ja: "2つの" },
      { en: "three",  ja: "3つの" },
      { en: "cat",    ja: "ねこ" },
      { en: "box",    ja: "箱" },
      { en: "dog",    ja: "犬" },
      { en: "four",   ja: "4つの" },
      { en: "five",   ja: "5つの" },
      { en: "orange", ja: "オレンジ" },
      { en: "bird",   ja: "鳥" },
      { en: "ball",   ja: "ボール" },
    ],
    sentences: [
      { ja: "私は2匹の犬を飼っています。",   tokens: ["I", "have", "two", "dogs"] },
      { ja: "私はりんごが好きです。",         tokens: ["I", "like", "apples"] },
      { ja: "私はたくさんの本を持っています。", tokens: ["I", "have", "many", "books"] },
      { ja: "私は3冊のノートを持っています。", tokens: ["I", "have", "three", "notebooks"] },
      { ja: "私はねこが好きです。",           tokens: ["I", "like", "cats"] },
      { ja: "私はペンを2本持っています。",     tokens: ["I", "have", "two", "pens"] },
      { ja: "私は4個のりんごを持っています。", tokens: ["I", "have", "four", "apples"] },
      { ja: "私は鳥が好きです。",             tokens: ["I", "like", "birds"] },
      { ja: "私は5冊の本を読みます。",         tokens: ["I", "read", "five", "books"] },
      { ja: "私はボールを3個持っています。",   tokens: ["I", "have", "three", "balls"] },
    ],
  },

  // ============================================================
  {
    id: "u4",
    title: "Unit 4　疑問詞（What / Who / Where）",
    words: [
      { en: "what",     ja: "何" },
      { en: "who",      ja: "だれ" },
      { en: "where",    ja: "どこ" },
      { en: "when",     ja: "いつ" },
      { en: "how",      ja: "どうやって・どのくらい" },
      { en: "why",      ja: "なぜ" },
      { en: "which",    ja: "どちら" },
      { en: "whose",    ja: "だれの" },
      { en: "time",     ja: "時間" },
      { en: "color",    ja: "色" },
      { en: "today",    ja: "今日" },
      { en: "favorite", ja: "お気に入りの" },
      { en: "subject",  ja: "教科" },
      { en: "sport",    ja: "スポーツ" },
      { en: "animal",   ja: "動物" },
    ],
    sentences: [
      { ja: "あなたは何が好きですか。",             tokens: ["What", "do", "you", "like"] },
      { ja: "これは何ですか。",                     tokens: ["What", "is", "this"] },
      { ja: "あなたはどこの出身ですか。",           tokens: ["Where", "are", "you", "from"] },
      { ja: "あなたはだれですか。",                 tokens: ["Who", "are", "you"] },
      { ja: "今何時ですか。",                       tokens: ["What", "time", "is", "it"] },
      { ja: "あなたはサッカーが好きですか。",       tokens: ["Do", "you", "like", "soccer"] },
      { ja: "あなたのお気に入りの教科は何ですか。", tokens: ["What", "is", "your", "favorite", "subject"] },
      { ja: "あなたはいつ勉強しますか。",           tokens: ["When", "do", "you", "study"] },
      { ja: "あなたはどんなスポーツが好きですか。", tokens: ["What", "sport", "do", "you", "like"] },
      { ja: "これは何色ですか。",                   tokens: ["What", "color", "is", "this"] },
    ],
  },

  // ============================================================
  {
    id: "u5",
    title: "Unit 5　助動詞 can（〜できる）",
    words: [
      { en: "can",   ja: "〜できる" },
      { en: "swim",  ja: "泳ぐ" },
      { en: "run",   ja: "走る" },
      { en: "sing",  ja: "歌う" },
      { en: "cook",  ja: "料理する" },
      { en: "dance", ja: "踊る" },
      { en: "read",  ja: "読む" },
      { en: "write", ja: "書く" },
      { en: "jump",  ja: "跳ぶ" },
      { en: "fast",  ja: "速く" },
      { en: "well",  ja: "上手に" },
      { en: "ski",   ja: "スキーをする" },
      { en: "draw",  ja: "（絵を）描く" },
      { en: "climb", ja: "登る" },
      { en: "high",  ja: "高く" },
    ],
    sentences: [
      { ja: "私は泳ぐことができます。",       tokens: ["I", "can", "swim"] },
      { ja: "私は速く走ることができます。",   tokens: ["I", "can", "run", "fast"] },
      { ja: "あなたは上手に歌えます。",       tokens: ["You", "can", "sing", "well"] },
      { ja: "私はギターを弾けます。",         tokens: ["I", "can", "play", "the", "guitar"] },
      { ja: "あなたは英語を話せますか。",     tokens: ["Can", "you", "speak", "English"] },
      { ja: "私はピアノを弾けます。",         tokens: ["I", "can", "play", "the", "piano"] },
      { ja: "私はスキーができます。",         tokens: ["I", "can", "ski"] },
      { ja: "私は絵を上手に描けます。",       tokens: ["I", "can", "draw", "well"] },
      { ja: "彼は高く跳べます。",             tokens: ["He", "can", "jump", "high"] },
      { ja: "あなたは速く泳げますか。",       tokens: ["Can", "you", "swim", "fast"] },
    ],
  },

  // ============================================================
  {
    id: "u6",
    title: "Unit 6　三人称単数（he / she + s）",
    words: [
      { en: "he",      ja: "彼は" },
      { en: "she",     ja: "彼女は" },
      { en: "likes",   ja: "好む（三単現）" },
      { en: "plays",   ja: "する（三単現）" },
      { en: "has",     ja: "持っている（三単現）" },
      { en: "watch",   ja: "見る" },
      { en: "live",    ja: "住む" },
      { en: "teacher", ja: "先生" },
      { en: "mother",  ja: "母" },
      { en: "father",  ja: "父" },
      { en: "studies", ja: "勉強する（三単現）" },
      { en: "goes",    ja: "行く（三単現）" },
      { en: "sister",  ja: "姉・妹" },
      { en: "brother", ja: "兄・弟" },
      { en: "speaks",  ja: "話す（三単現）" },
    ],
    sentences: [
      { ja: "彼はサッカーが好きです。",       tokens: ["He", "likes", "soccer"] },
      { ja: "彼女はピアノを弾きます。",       tokens: ["She", "plays", "the", "piano"] },
      { ja: "彼は犬を飼っています。",         tokens: ["He", "has", "a", "dog"] },
      { ja: "私の母は英語を教えます。",       tokens: ["My", "mother", "teaches", "English"] },
      { ja: "彼女は東京に住んでいます。",     tokens: ["She", "lives", "in", "Tokyo"] },
      { ja: "私の父はテレビを見ます。",       tokens: ["My", "father", "watches", "TV"] },
      { ja: "彼は毎日英語を勉強します。",     tokens: ["He", "studies", "English", "every", "day"] },
      { ja: "彼女は学校に行きます。",         tokens: ["She", "goes", "to", "school"] },
      { ja: "私の姉は音楽が好きです。",       tokens: ["My", "sister", "likes", "music"] },
      { ja: "彼は英語を話します。",           tokens: ["He", "speaks", "English"] },
    ],
  },

  // ============================================================
  {
    id: "u7",
    title: "Unit 7　現在進行形（be + ~ing）",
    words: [
      { en: "now",      ja: "今" },
      { en: "running",  ja: "走っている" },
      { en: "playing",  ja: "している" },
      { en: "eating",   ja: "食べている" },
      { en: "studying", ja: "勉強している" },
      { en: "reading",  ja: "読んでいる" },
      { en: "watching", ja: "見ている" },
      { en: "singing",  ja: "歌っている" },
      { en: "sleeping", ja: "眠っている" },
      { en: "cooking",  ja: "料理している" },
      { en: "writing",  ja: "書いている" },
      { en: "swimming", ja: "泳いでいる" },
      { en: "dancing",  ja: "踊っている" },
      { en: "walking",  ja: "歩いている" },
      { en: "making",   ja: "作っている" },
    ],
    sentences: [
      { ja: "私は今英語を勉強しています。",   tokens: ["I", "am", "studying", "English", "now"] },
      { ja: "彼はサッカーをしています。",     tokens: ["He", "is", "playing", "soccer"] },
      { ja: "彼女は本を読んでいます。",       tokens: ["She", "is", "reading", "a", "book"] },
      { ja: "私は昼ごはんを食べています。",   tokens: ["I", "am", "eating", "lunch"] },
      { ja: "彼らは歌っています。",           tokens: ["They", "are", "singing"] },
      { ja: "私の母は料理をしています。",     tokens: ["My", "mother", "is", "cooking"] },
      { ja: "彼女は今泳いでいます。",         tokens: ["She", "is", "swimming", "now"] },
      { ja: "私は手紙を書いています。",       tokens: ["I", "am", "writing", "a", "letter"] },
      { ja: "彼らは踊っています。",           tokens: ["They", "are", "dancing"] },
      { ja: "私の父は歩いています。",         tokens: ["My", "father", "is", "walking"] },
    ],
  },

  // ============================================================
  {
    id: "u8",
    title: "Unit 8　過去形（played / went / was）",
    words: [
      { en: "yesterday", ja: "昨日" },
      { en: "played",    ja: "した（過去）" },
      { en: "went",      ja: "行った" },
      { en: "ate",       ja: "食べた" },
      { en: "studied",   ja: "勉強した" },
      { en: "was",       ja: "〜だった（I / he）" },
      { en: "were",      ja: "〜だった（you / they）" },
      { en: "saw",       ja: "見た" },
      { en: "enjoyed",   ja: "楽しんだ" },
      { en: "busy",      ja: "忙しい" },
      { en: "watched",   ja: "見た（過去）" },
      { en: "had",       ja: "持っていた" },
      { en: "last",      ja: "この前の" },
      { en: "made",      ja: "作った" },
      { en: "came",      ja: "来た" },
    ],
    sentences: [
      { ja: "私は昨日サッカーをしました。",   tokens: ["I", "played", "soccer", "yesterday"] },
      { ja: "私は昨日公園に行きました。",     tokens: ["I", "went", "to", "the", "park", "yesterday"] },
      { ja: "私は昨日英語を勉強しました。",   tokens: ["I", "studied", "English", "yesterday"] },
      { ja: "私は昨日うれしかったです。",     tokens: ["I", "was", "happy", "yesterday"] },
      { ja: "あなたは昨日忙しかったです。",   tokens: ["You", "were", "busy", "yesterday"] },
      { ja: "私は映画を楽しみました。",       tokens: ["I", "enjoyed", "the", "movie"] },
      { ja: "私は昨日テレビを見ました。",     tokens: ["I", "watched", "TV", "yesterday"] },
      { ja: "私は犬を飼っていました。",       tokens: ["I", "had", "a", "dog"] },
      { ja: "私は先週京都に行きました。",     tokens: ["I", "went", "to", "Kyoto", "last", "week"] },
      { ja: "彼女は昨日忙しかったです。",     tokens: ["She", "was", "busy", "yesterday"] },
    ],
  },

  // ============================================================
  {
    id: "u9",
    title: "Unit 9　命令文・Let's（〜しなさい / 〜しよう）",
    words: [
      { en: "open",    ja: "開ける" },
      { en: "close",   ja: "閉める" },
      { en: "stand",   ja: "立つ" },
      { en: "sit",     ja: "座る" },
      { en: "look",    ja: "目を向ける・見る" },
      { en: "listen",  ja: "聞く" },
      { en: "please",  ja: "どうぞ・ください" },
      { en: "let's",   ja: "〜しよう" },
      { en: "stop",    ja: "止まる・やめる" },
      { en: "come",    ja: "来る" },
      { en: "wait",    ja: "待つ" },
      { en: "careful", ja: "注意して" },
    ],
    sentences: [
      { ja: "立ってください。",       tokens: ["Please", "stand", "up"] },
      { ja: "すわってください。",     tokens: ["Please", "sit", "down"] },
      { ja: "ドアを開けてください。", tokens: ["Please", "open", "the", "door"] },
      { ja: "黒板を見て。",           tokens: ["Look", "at", "the", "blackboard"] },
      { ja: "私の話を聞いて。",       tokens: ["Listen", "to", "me"] },
      { ja: "サッカーをしよう。",     tokens: ["Let's", "play", "soccer"] },
      { ja: "いっしょに歌おう。",     tokens: ["Let's", "sing", "together"] },
      { ja: "気をつけて。",           tokens: ["Be", "careful"] },
    ],
  },

  // ============================================================
  {
    id: "u10",
    title: "Unit 10　前置詞・場所（in / on / There is）",
    words: [
      { en: "in",    ja: "〜の中に" },
      { en: "on",    ja: "〜の上に" },
      { en: "under", ja: "〜の下に" },
      { en: "by",    ja: "〜のそばに" },
      { en: "near",  ja: "〜の近くに" },
      { en: "here",  ja: "ここに" },
      { en: "there", ja: "そこに" },
      { en: "desk",  ja: "机" },
      { en: "room",  ja: "部屋" },
      { en: "table", ja: "テーブル" },
      { en: "wall",  ja: "かべ" },
      { en: "park",  ja: "公園" },
    ],
    sentences: [
      { ja: "ねこは箱の中にいます。",             tokens: ["The", "cat", "is", "in", "the", "box"] },
      { ja: "本は机の上にあります。",             tokens: ["The", "book", "is", "on", "the", "desk"] },
      { ja: "ボールはいすの下にあります。",       tokens: ["The", "ball", "is", "under", "the", "chair"] },
      { ja: "かばんはテーブルのそばにあります。", tokens: ["The", "bag", "is", "by", "the", "table"] },
      { ja: "部屋に犬が1匹います。",             tokens: ["There", "is", "a", "dog", "in", "the", "room"] },
      { ja: "公園に2匹のねこがいます。",         tokens: ["There", "are", "two", "cats", "in", "the", "park"] },
      { ja: "私の家の近くに学校があります。",     tokens: ["There", "is", "a", "school", "near", "my", "house"] },
      { ja: "私はここにいます。",                 tokens: ["I", "am", "here"] },
    ],
  },

  // ============================================================
  {
    id: "u11",
    title: "Unit 11　曜日・月・季節",
    words: [
      { en: "Monday",   ja: "月曜日" },
      { en: "Tuesday",  ja: "火曜日" },
      { en: "Sunday",   ja: "日曜日" },
      { en: "morning",  ja: "朝" },
      { en: "week",     ja: "週" },
      { en: "month",    ja: "月（暦）" },
      { en: "year",     ja: "年" },
      { en: "spring",   ja: "春" },
      { en: "summer",   ja: "夏" },
      { en: "winter",   ja: "冬" },
      { en: "January",  ja: "1月" },
      { en: "December", ja: "12月" },
    ],
    sentences: [
      { ja: "今日は月曜日です。",                 tokens: ["It", "is", "Monday", "today"] },
      { ja: "私は日曜日にサッカーをします。",     tokens: ["I", "play", "soccer", "on", "Sunday"] },
      { ja: "私は毎朝走ります。",                 tokens: ["I", "run", "every", "morning"] },
      { ja: "私は夏が好きです。",                 tokens: ["I", "like", "summer"] },
      { ja: "私の誕生日は12月です。",             tokens: ["My", "birthday", "is", "in", "December"] },
      { ja: "私たちは月曜日に英語を勉強します。", tokens: ["We", "study", "English", "on", "Monday"] },
      { ja: "春は暖かいです。",                   tokens: ["Spring", "is", "warm"] },
      { ja: "冬は寒いです。",                     tokens: ["Winter", "is", "cold"] },
    ],
  },

  // ============================================================
  {
    id: "u12",
    title: "Unit 12　数と年齢（How many / How old）",
    words: [
      { en: "old",     ja: "年をとった・古い" },
      { en: "six",     ja: "6" },
      { en: "seven",   ja: "7" },
      { en: "eight",   ja: "8" },
      { en: "nine",    ja: "9" },
      { en: "ten",     ja: "10" },
      { en: "twelve",  ja: "12" },
      { en: "twenty",  ja: "20" },
      { en: "hundred", ja: "100" },
      { en: "number",  ja: "数" },
      { en: "years",   ja: "年（複数）" },
      { en: "age",     ja: "年齢" },
    ],
    sentences: [
      { ja: "あなたは何冊の本を持っていますか。",   tokens: ["How", "many", "books", "do", "you", "have"] },
      { ja: "私は本を6冊持っています。",           tokens: ["I", "have", "six", "books"] },
      { ja: "あなたは何歳ですか。",                 tokens: ["How", "old", "are", "you"] },
      { ja: "私は12歳です。",                       tokens: ["I", "am", "twelve", "years", "old"] },
      { ja: "私のクラスには30人の生徒がいます。",   tokens: ["There", "are", "thirty", "students", "in", "my", "class"] },
      { ja: "私は7時に起きます。",                 tokens: ["I", "get", "up", "at", "seven"] },
      { ja: "彼は10歳です。",                       tokens: ["He", "is", "ten", "years", "old"] },
      { ja: "りんごがいくつかあります。",           tokens: ["There", "are", "some", "apples"] },
    ],
  },

  // ============================================================
  {
    id: "u13",
    title: "Unit 13　家族と人",
    words: [
      { en: "family",      ja: "家族" },
      { en: "grandmother", ja: "祖母" },
      { en: "grandfather", ja: "祖父" },
      { en: "parents",     ja: "両親" },
      { en: "baby",        ja: "赤ちゃん" },
      { en: "boy",         ja: "男の子" },
      { en: "girl",        ja: "女の子" },
      { en: "people",      ja: "人々" },
      { en: "aunt",        ja: "おば" },
      { en: "uncle",       ja: "おじ" },
      { en: "woman",       ja: "女性" },
      { en: "man",         ja: "男性" },
    ],
    sentences: [
      { ja: "これは私の家族です。",           tokens: ["This", "is", "my", "family"] },
      { ja: "彼は私の祖父です。",             tokens: ["He", "is", "my", "grandfather"] },
      { ja: "彼女は私の祖母です。",           tokens: ["She", "is", "my", "grandmother"] },
      { ja: "あの男の子は私の友達です。",     tokens: ["That", "boy", "is", "my", "friend"] },
      { ja: "あの女の子は私の妹です。",       tokens: ["That", "girl", "is", "my", "sister"] },
      { ja: "私には2人の兄弟がいます。",       tokens: ["I", "have", "two", "brothers"] },
      { ja: "私の両親は親切です。",           tokens: ["My", "parents", "are", "kind"] },
      { ja: "彼らは私のおじとおばです。",     tokens: ["They", "are", "my", "uncle", "and", "aunt"] },
    ],
  },

  // ============================================================
  {
    id: "u14",
    title: "Unit 14　食べ物・飲み物",
    words: [
      { en: "rice",      ja: "ごはん・米" },
      { en: "bread",     ja: "パン" },
      { en: "milk",      ja: "牛乳" },
      { en: "egg",       ja: "卵" },
      { en: "fish",      ja: "魚" },
      { en: "meat",      ja: "肉" },
      { en: "fruit",     ja: "くだもの" },
      { en: "vegetable", ja: "野菜" },
      { en: "tea",       ja: "お茶" },
      { en: "juice",     ja: "ジュース" },
      { en: "cake",      ja: "ケーキ" },
      { en: "lunch",     ja: "昼食" },
    ],
    sentences: [
      { ja: "私は朝ごはんにパンを食べます。",     tokens: ["I", "eat", "bread", "for", "breakfast"] },
      { ja: "私は牛乳を飲みます。",               tokens: ["I", "drink", "milk"] },
      { ja: "私は魚が好きです。",                 tokens: ["I", "like", "fish"] },
      { ja: "私はくだものを食べたいです。",       tokens: ["I", "want", "to", "eat", "fruit"] },
      { ja: "私はケーキが大好きです。",           tokens: ["I", "love", "cake"] },
      { ja: "私はお昼にごはんを食べます。",       tokens: ["I", "eat", "rice", "for", "lunch"] },
      { ja: "私はお茶を飲みません。",             tokens: ["I", "do", "not", "drink", "tea"] },
      { ja: "私は野菜が好きです。",               tokens: ["I", "like", "vegetables"] },
    ],
  },

  // ============================================================
  {
    id: "u15",
    title: "Unit 15　様子・気持ち（形容詞）",
    words: [
      { en: "big",       ja: "大きい" },
      { en: "small",     ja: "小さい" },
      { en: "long",      ja: "長い" },
      { en: "short",     ja: "短い" },
      { en: "new",       ja: "新しい" },
      { en: "cute",      ja: "かわいい" },
      { en: "cold",      ja: "寒い・冷たい" },
      { en: "hot",       ja: "暑い・熱い" },
      { en: "sad",       ja: "悲しい" },
      { en: "kind",      ja: "親切な" },
      { en: "beautiful", ja: "美しい" },
      { en: "tired",     ja: "疲れた" },
    ],
    sentences: [
      { ja: "この犬は大きいです。",           tokens: ["This", "dog", "is", "big"] },
      { ja: "あのねこは小さいです。",         tokens: ["That", "cat", "is", "small"] },
      { ja: "私は新しい自転車を持っています。", tokens: ["I", "have", "a", "new", "bike"] },
      { ja: "このケーキはとてもおいしいです。", tokens: ["This", "cake", "is", "very", "good"] },
      { ja: "私は今日とても疲れています。",     tokens: ["I", "am", "very", "tired", "today"] },
      { ja: "彼女はとても親切です。",         tokens: ["She", "is", "very", "kind"] },
      { ja: "その花は美しいです。",           tokens: ["The", "flower", "is", "beautiful"] },
      { ja: "私のねこはかわいいです。",       tokens: ["My", "cat", "is", "cute"] },
    ],
  },

  // ============================================================
  {
    id: "u16",
    title: "Unit 16　学校・身の回りのもの",
    words: [
      { en: "school",     ja: "学校" },
      { en: "classroom",  ja: "教室" },
      { en: "pencil",     ja: "えんぴつ" },
      { en: "eraser",     ja: "消しゴム" },
      { en: "notebook",   ja: "ノート" },
      { en: "ruler",      ja: "じょうぎ" },
      { en: "dictionary", ja: "辞書" },
      { en: "computer",   ja: "コンピューター" },
      { en: "clock",      ja: "時計" },
      { en: "window",     ja: "窓" },
      { en: "chair",      ja: "いす" },
      { en: "blackboard", ja: "黒板" },
    ],
    sentences: [
      { ja: "これは私の教室です。",                 tokens: ["This", "is", "my", "classroom"] },
      { ja: "私はえんぴつを3本持っています。",       tokens: ["I", "have", "three", "pencils"] },
      { ja: "これはあなたの辞書ですか。",           tokens: ["Is", "this", "your", "dictionary"] },
      { ja: "私の学校は大きいです。",               tokens: ["My", "school", "is", "big"] },
      { ja: "私は新しいコンピューターがほしいです。", tokens: ["I", "want", "a", "new", "computer"] },
      { ja: "時計はかべにあります。",               tokens: ["The", "clock", "is", "on", "the", "wall"] },
      { ja: "いすに座ってください。",               tokens: ["Please", "sit", "on", "the", "chair"] },
      { ja: "窓を開けてください。",                 tokens: ["Please", "open", "the", "window"] },
    ],
  },
];

// むずかしいモード用のダミー単語プール（語順とは関係ない おとり）
const DUMMY_POOL = ["he", "she", "is", "the", "a", "my", "your", "in", "on", "and", "not", "very", "do", "they"];
