// ===== 中1 えいごドリル：問題データ =====
// 光村「Here We Go!」の単元構成に寄せた中1標準のオリジナル問題。
// 教科書と完全一致ではありません。あとから自由に追加・差し替えできます。
//
// words: { en:英単語, ja:日本語 }
// sentences: { ja:日本語文, tokens:[正しい語順の英単語] }
//   ※ ピリオドや「？」は自動表示。tokens には単語だけを入れる。先頭は大文字で。

const UNITS = [
  // ============================================================
  {
    id: "u1",
    title: "Unit 1　自己紹介（be動詞 am / are）",
    words: [
      { en: "I",       ja: "私は" },
      { en: "you",     ja: "あなたは" },
      { en: "am",      ja: "〜です（I のとき）" },
      { en: "are",     ja: "〜です（you のとき）" },
      { en: "name",    ja: "名前" },
      { en: "friend",  ja: "友達" },
      { en: "student", ja: "生徒・学生" },
      { en: "happy",   ja: "うれしい" },
      { en: "from",    ja: "〜出身で" },
      { en: "nice",    ja: "素敵な・良い" },
      { en: "this",    ja: "これは" },
      { en: "is",      ja: "〜です（he / it のとき）" },
      { en: "hungry",  ja: "おなかがすいた" },
      { en: "fine",    ja: "元気な" },
      { en: "great",   ja: "すばらしい" },
    ],
    sentences: [
      { ja: "私は学生です。",         tokens: ["I", "am", "a", "student"] },
      { ja: "あなたは私の友達です。",   tokens: ["You", "are", "my", "friend"] },
      { ja: "私はうれしいです。",       tokens: ["I", "am", "happy"] },
      { ja: "私はケンです。",          tokens: ["I", "am", "Ken"] },
      { ja: "あなたは素敵です。",       tokens: ["You", "are", "nice"] },
      { ja: "私は大阪出身です。",       tokens: ["I", "am", "from", "Osaka"] },
      { ja: "これはペンです。",         tokens: ["This", "is", "a", "pen"] },
      { ja: "私は元気です。",          tokens: ["I", "am", "fine"] },
      { ja: "私はおなかがすいています。", tokens: ["I", "am", "hungry"] },
      { ja: "あなたはすばらしいです。",  tokens: ["You", "are", "great"] },
    ],
  },

  // ============================================================
  {
    id: "u2",
    title: "Unit 2　一般動詞（like / play / have）",
    words: [
      { en: "like",   ja: "好きだ" },
      { en: "play",   ja: "（スポーツ・楽器を）する" },
      { en: "have",   ja: "持っている・飼っている" },
      { en: "want",   ja: "ほしい" },
      { en: "eat",    ja: "食べる" },
      { en: "study",  ja: "勉強する" },
      { en: "know",   ja: "知っている" },
      { en: "go",     ja: "行く" },
      { en: "speak",  ja: "話す" },
      { en: "music",  ja: "音楽" },
      { en: "drink",  ja: "飲む" },
      { en: "use",    ja: "使う" },
      { en: "help",   ja: "助ける" },
      { en: "make",   ja: "作る" },
      { en: "tennis", ja: "テニス" },
    ],
    sentences: [
      { ja: "私はサッカーが好きです。",       tokens: ["I", "like", "soccer"] },
      { ja: "私は毎日英語を勉強します。",     tokens: ["I", "study", "English", "every", "day"] },
      { ja: "私はギターを弾きます。",         tokens: ["I", "play", "the", "guitar"] },
      { ja: "私は犬を飼っています。",         tokens: ["I", "have", "a", "dog"] },
      { ja: "私は音楽が好きです。",           tokens: ["I", "like", "music"] },
      { ja: "私は朝ごはんを食べます。",       tokens: ["I", "eat", "breakfast"] },
      { ja: "私は水を飲みます。",             tokens: ["I", "drink", "water"] },
      { ja: "私はテニスをします。",           tokens: ["I", "play", "tennis"] },
      { ja: "私は数学が好きです。",           tokens: ["I", "like", "math"] },
      { ja: "私は新しいかばんがほしいです。", tokens: ["I", "want", "a", "new", "bag"] },
    ],
  },

  // ============================================================
  {
    id: "u3",
    title: "Unit 3　名詞の複数形と数",
    words: [
      { en: "many",   ja: "たくさんの" },
      { en: "some",   ja: "いくつかの" },
      { en: "book",   ja: "本" },
      { en: "apple",  ja: "りんご" },
      { en: "pen",    ja: "ペン" },
      { en: "two",    ja: "2つの" },
      { en: "three",  ja: "3つの" },
      { en: "cat",    ja: "ねこ" },
      { en: "box",    ja: "箱" },
      { en: "dog",    ja: "犬" },
      { en: "four",   ja: "4つの" },
      { en: "five",   ja: "5つの" },
      { en: "orange", ja: "オレンジ" },
      { en: "bird",   ja: "鳥" },
      { en: "ball",   ja: "ボール" },
    ],
    sentences: [
      { ja: "私は2匹の犬を飼っています。",   tokens: ["I", "have", "two", "dogs"] },
      { ja: "私はりんごが好きです。",         tokens: ["I", "like", "apples"] },
      { ja: "私はたくさんの本を持っています。", tokens: ["I", "have", "many", "books"] },
      { ja: "私は3冊のノートを持っています。", tokens: ["I", "have", "three", "notebooks"] },
      { ja: "私はねこが好きです。",           tokens: ["I", "like", "cats"] },
      { ja: "私はペンを2本持っています。",     tokens: ["I", "have", "two", "pens"] },
      { ja: "私は4個のりんごを持っています。", tokens: ["I", "have", "four", "apples"] },
      { ja: "私は鳥が好きです。",             tokens: ["I", "like", "birds"] },
      { ja: "私は5冊の本を読みます。",         tokens: ["I", "read", "five", "books"] },
      { ja: "私はボールを3個持っています。",   tokens: ["I", "have", "three", "balls"] },
    ],
  },

  // ============================================================
  {
    id: "u4",
    title: "Unit 4　疑問詞（What / Who / Where）",
    words: [
      { en: "what",     ja: "何" },
      { en: "who",      ja: "だれ" },
      { en: "where",    ja: "どこ" },
      { en: "when",     ja: "いつ" },
      { en: "how",      ja: "どうやって・どのくらい" },
      { en: "why",      ja: "なぜ" },
      { en: "which",    ja: "どちら" },
      { en: "whose",    ja: "だれの" },
      { en: "time",     ja: "時間" },
      { en: "color",    ja: "色" },
      { en: "today",    ja: "今日" },
      { en: "favorite", ja: "お気に入りの" },
      { en: "subject",  ja: "教科" },
      { en: "sport",    ja: "スポーツ" },
      { en: "animal",   ja: "動物" },
    ],
    sentences: [
      { ja: "あなたは何が好きですか。",             tokens: ["What", "do", "you", "like"] },
      { ja: "これは何ですか。",                     tokens: ["What", "is", "this"] },
      { ja: "あなたはどこの出身ですか。",           tokens: ["Where", "are", "you", "from"] },
      { ja: "あなたはだれですか。",                 tokens: ["Who", "are", "you"] },
      { ja: "今何時ですか。",                       tokens: ["What", "time", "is", "it"] },
      { ja: "あなたはサッカーが好きですか。",       tokens: ["Do", "you", "like", "soccer"] },
      { ja: "あなたのお気に入りの教科は何ですか。", tokens: ["What", "is", "your", "favorite", "subject"] },
      { ja: "あなたはいつ勉強しますか。",           tokens: ["When", "do", "you", "study"] },
      { ja: "あなたはどんなスポーツが好きですか。", tokens: ["What", "sport", "do", "you", "like"] },
      { ja: "これは何色ですか。",                   tokens: ["What", "color", "is", "this"] },
    ],
  },

  // ============================================================
  {
    id: "u5",
    title: "Unit 5　助動詞 can（〜できる）",
    words: [
      { en: "can",   ja: "〜できる" },
      { en: "swim",  ja: "泳ぐ" },
      { en: "run",   ja: "走る" },
      { en: "sing",  ja: "歌う" },
      { en: "cook",  ja: "料理する" },
      { en: "dance", ja: "踊る" },
      { en: "read",  ja: "読む" },
      { en: "write", ja: "書く" },
      { en: "jump",  ja: "跳ぶ" },
      { en: "fast",  ja: "速く" },
      { en: "well",  ja: "上手に" },
      { en: "ski",   ja: "スキーをする" },
      { en: "draw",  ja: "（絵を）描く" },
      { en: "climb", ja: "登る" },
      { en: "high",  ja: "高く" },
    ],
    sentences: [
      { ja: "私は泳ぐことができます。",       tokens: ["I", "can", "swim"] },
      { ja: "私は速く走ることができます。",   tokens: ["I", "can", "run", "fast"] },
      { ja: "あなたは上手に歌えます。",       tokens: ["You", "can", "sing", "well"] },
      { ja: "私はギターを弾けます。",         tokens: ["I", "can", "play", "the", "guitar"] },
      { ja: "あなたは英語を話せますか。",     tokens: ["Can", "you", "speak", "English"] },
      { ja: "私はピアノを弾けます。",         tokens: ["I", "can", "play", "the", "piano"] },
      { ja: "私はスキーができます。",         tokens: ["I", "can", "ski"] },
      { ja: "私は絵を上手に描けます。",       tokens: ["I", "can", "draw", "well"] },
      { ja: "彼は高く跳べます。",             tokens: ["He", "can", "jump", "high"] },
      { ja: "あなたは速く泳げますか。",       tokens: ["Can", "you", "swim", "fast"] },
    ],
  },

  // ============================================================
  {
    id: "u6",
    title: "Unit 6　三人称単数（he / she + s）",
    words: [
      { en: "he",      ja: "彼は" },
      { en: "she",     ja: "彼女は" },
      { en: "likes",   ja: "好む（三単現）" },
      { en: "plays",   ja: "する（三単現）" },
      { en: "has",     ja: "持っている（三単現）" },
      { en: "watch",   ja: "見る" },
      { en: "live",    ja: "住む" },
      { en: "teacher", ja: "先生" },
      { en: "mother",  ja: "母" },
      { en: "father",  ja: "父" },
      { en: "studies", ja: "勉強する（三単現）" },
      { en: "goes",    ja: "行く（三単現）" },
      { en: "sister",  ja: "姉・妹" },
      { en: "brother", ja: "兄・弟" },
      { en: "speaks",  ja: "話す（三単現）" },
    ],
    sentences: [
      { ja: "彼はサッカーが好きです。",       tokens: ["He", "likes", "soccer"] },
      { ja: "彼女はピアノを弾きます。",       tokens: ["She", "plays", "the", "piano"] },
      { ja: "彼は犬を飼っています。",         tokens: ["He", "has", "a", "dog"] },
      { ja: "私の母は英語を教えます。",       tokens: ["My", "mother", "teaches", "English"] },
      { ja: "彼女は東京に住んでいます。",     tokens: ["She", "lives", "in", "Tokyo"] },
      { ja: "私の父はテレビを見ます。",       tokens: ["My", "father", "watches", "TV"] },
      { ja: "彼は毎日英語を勉強します。",     tokens: ["He", "studies", "English", "every", "day"] },
      { ja: "彼女は学校に行きます。",         tokens: ["She", "goes", "to", "school"] },
      { ja: "私の姉は音楽が好きです。",       tokens: ["My", "sister", "likes", "music"] },
      { ja: "彼は英語を話します。",           tokens: ["He", "speaks", "English"] },
    ],
  },

  // ============================================================
  {
    id: "u7",
    title: "Unit 7　現在進行形（be + ~ing）",
    words: [
      { en: "now",      ja: "今" },
      { en: "running",  ja: "走っている" },
      { en: "playing",  ja: "している" },
      { en: "eating",   ja: "食べている" },
      { en: "studying", ja: "勉強している" },
      { en: "reading",  ja: "読んでいる" },
      { en: "watching", ja: "見ている" },
      { en: "singing",  ja: "歌っている" },
      { en: "sleeping", ja: "眠っている" },
      { en: "cooking",  ja: "料理している" },
      { en: "writing",  ja: "書いている" },
      { en: "swimming", ja: "泳いでいる" },
      { en: "dancing",  ja: "踊っている" },
      { en: "walking",  ja: "歩いている" },
      { en: "making",   ja: "作っている" },
    ],
    sentences: [
      { ja: "私は今英語を勉強しています。",   tokens: ["I", "am", "studying", "English", "now"] },
      { ja: "彼はサッカーをしています。",     tokens: ["He", "is", "playing", "soccer"] },
      { ja: "彼女は本を読んでいます。",       tokens: ["She", "is", "reading", "a", "book"] },
      { ja: "私は昼ごはんを食べています。",   tokens: ["I", "am", "eating", "lunch"] },
      { ja: "彼らは歌っています。",           tokens: ["They", "are", "singing"] },
      { ja: "私の母は料理をしています。",     tokens: ["My", "mother", "is", "cooking"] },
      { ja: "彼女は今泳いでいます。",         tokens: ["She", "is", "swimming", "now"] },
      { ja: "私は手紙を書いています。",       tokens: ["I", "am", "writing", "a", "letter"] },
      { ja: "彼らは踊っています。",           tokens: ["They", "are", "dancing"] },
      { ja: "私の父は歩いています。",         tokens: ["My", "father", "is", "walking"] },
    ],
  },

  // ============================================================
  {
    id: "u8",
    title: "Unit 8　過去形（played / went / was）",
    words: [
      { en: "yesterday", ja: "昨日" },
      { en: "played",    ja: "した（過去）" },
      { en: "went",      ja: "行った" },
      { en: "ate",       ja: "食べた" },
      { en: "studied",   ja: "勉強した" },
      { en: "was",       ja: "〜だった（I / he）" },
      { en: "were",      ja: "〜だった（you / they）" },
      { en: "saw",       ja: "見た" },
      { en: "enjoyed",   ja: "楽しんだ" },
      { en: "busy",      ja: "忙しい" },
      { en: "watched",   ja: "見た（過去）" },
      { en: "had",       ja: "持っていた" },
      { en: "last",      ja: "この前の" },
      { en: "made",      ja: "作った" },
      { en: "came",      ja: "来た" },
    ],
    sentences: [
      { ja: "私は昨日サッカーをしました。",   tokens: ["I", "played", "soccer", "yesterday"] },
      { ja: "私は昨日公園に行きました。",     tokens: ["I", "went", "to", "the", "park", "yesterday"] },
      { ja: "私は昨日英語を勉強しました。",   tokens: ["I", "studied", "English", "yesterday"] },
      { ja: "私は昨日うれしかったです。",     tokens: ["I", "was", "happy", "yesterday"] },
      { ja: "あなたは昨日忙しかったです。",   tokens: ["You", "were", "busy", "yesterday"] },
      { ja: "私は映画を楽しみました。",       tokens: ["I", "enjoyed", "the", "movie"] },
      { ja: "私は昨日テレビを見ました。",     tokens: ["I", "watched", "TV", "yesterday"] },
      { ja: "私は犬を飼っていました。",       tokens: ["I", "had", "a", "dog"] },
      { ja: "私は先週京都に行きました。",     tokens: ["I", "went", "to", "Kyoto", "last", "week"] },
      { ja: "彼女は昨日忙しかったです。",     tokens: ["She", "was", "busy", "yesterday"] },
    ],
  },
];

// むずかしいモード用のダミー単語プール（語順とは関係ない おとり）
const DUMMY_POOL = ["he", "she", "is", "the", "a", "my", "your", "in", "on", "and", "not", "very", "do", "they"];
